apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:                           # ❗️Fixed: was `sepc`
      containers:
        - name: java-app
          image: ganesh6498/java-sonar-harness:latest  # ❗️Removed space before `latest`
          ports:                              # ❗️Fixed: was `port` (should be plural)
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: java-service
spec:                                  # ❗️Fixed: was `sepc`
  type: LoadBalancer
  selector:
    app: java
  ports:                               # ❗️Fixed: was `port` (should be plural)
    - port: 80
      targetPort: 8081

